export const docImages = [
    {   src: "/documents/large/dovidka1.jpg",
        thumbnail: "/documents/small/dovidka1.jpg",
        thumbnailWidth: 281,
        thumbnailHeight: 400,
        caption: "Довідка 1"},
    {   src: "/documents/large/dovidka2.jpg",
        thumbnail: "/documents/small/dovidka2.jpg",
        thumbnailWidth: 285,
        thumbnailHeight: 400,
        caption: "first image"},
    /*{   src: "/documents/large/statut1.jpg",
        thumbnail: "/documents/small/statut1.jpg",
        thumbnailWidth: 180,
        thumbnailHeight: 400,
        caption: "first image"},
    {   src: "/documents/large/statut2.jpg",
        thumbnail: "/documents/small/statut2.jpg",
        thumbnailWidth: 180,
        thumbnailHeight: 400,
        caption: "first image"},
    {   src: "/documents/large/statut3.jpg",
        thumbnail: "/documents/small/statut3.jpg",
        thumbnailWidth: 180,
        thumbnailHeight: 400,
        caption: "first image"},
    /*{   src: "/project/large/medic/6.jpg",
        thumbnail: "/project/small/medic/6.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/7.jpg",
        thumbnail: "/project/small/medic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/8.jpg",
        thumbnail: "/project/small/medic/8.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/9.jpg",
        thumbnail: "/project/small/medic/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/10.jpg",
        thumbnail: "/project/small/medic/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/11.jpg",
        thumbnail: "/project/small/medic/11.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/12.jpg",
        thumbnail: "/project/small/medic/12.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/13.jpg",
        thumbnail: "/project/small/medic/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/14.jpg",
        thumbnail: "/project/small/medic/14.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
*/
]