export const fondImages = [
    {   src: "/fond/diploma/large/diplom1.jpg",
        thumbnail: "/fond/diploma/small/diplom1.jpg",
        thumbnailWidth: 341,
        thumbnailHeight: 500,
        caption: "Довідка 1"},
    {   src: "/fond/diploma/large/diplom2.jpg",
        thumbnail: "/fond/diploma/small/diplom2.jpg",
        thumbnailWidth: 338,
        thumbnailHeight: 500,
        caption: "first image"},
    {   src: "/fond/diploma/large/diplom3.jpg",
        thumbnail: "/fond/diploma/small/diplom3.jpg",
        thumbnailWidth: 338,
        thumbnailHeight: 500,
        caption: "first image"},
    {   src: "/fond/diploma/large/diplom4.jpg",
        thumbnail: "/fond/diploma/small/diplom4.jpg",
        thumbnailWidth: 349,
        thumbnailHeight: 500,
        caption: "first image"},
    {   src: "/fond/diploma/large/diplom5.jpg",
        thumbnail: "/fond/diploma/small/diplom5.jpg",
        thumbnailWidth: 354,
        thumbnailHeight: 500,
        caption: "first image"},
    {   src: "/fond/diploma/large/diplom6.jpg",
        thumbnail: "/fond/diploma/small/diplom6.jpg",
        thumbnailWidth: 352,
        thumbnailHeight: 500,
        caption: "first image"},
    /*{   src: "/project/large/medic/7.jpg",
        thumbnail: "/project/small/medic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/8.jpg",
        thumbnail: "/project/small/medic/8.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/9.jpg",
        thumbnail: "/project/small/medic/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/10.jpg",
        thumbnail: "/project/small/medic/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/11.jpg",
        thumbnail: "/project/small/medic/11.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/12.jpg",
        thumbnail: "/project/small/medic/12.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/13.jpg",
        thumbnail: "/project/small/medic/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/14.jpg",
        thumbnail: "/project/small/medic/14.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
*/
]