export const medicImages = [
    {   src: "/project/large/medic/1.jpg",
        thumbnail: "/project/small/medic/1.jpg",
        thumbnailWidth: 113,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/2.jpg",
        thumbnail: "/project/small/medic/2.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/3.jpg",
        thumbnail: "/project/small/medic/3.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/4.jpg",
        thumbnail: "/project/small/medic/4.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/5.jpg",
        thumbnail: "/project/small/medic/5.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/6.jpg",
        thumbnail: "/project/small/medic/6.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/7.jpg",
        thumbnail: "/project/small/medic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/8.jpg",
        thumbnail: "/project/small/medic/8.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/9.jpg",
        thumbnail: "/project/small/medic/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/10.jpg",
        thumbnail: "/project/small/medic/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/11.jpg",
        thumbnail: "/project/small/medic/11.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/12.jpg",
        thumbnail: "/project/small/medic/12.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/13.jpg",
        thumbnail: "/project/small/medic/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/14.jpg",
        thumbnail: "/project/small/medic/14.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const ammunImages = [
    {   src: "/project/large/ammun/1.jpg",
        thumbnail: "/project/small/ammun/1.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/2.jpg",
        thumbnail: "/project/small/ammun/2.jpg",
        thumbnailWidth: 356,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/3.jpg",
        thumbnail: "/project/small/ammun/3.jpg",
        thumbnailWidth: 356,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/4.jpg",
        thumbnail: "/project/small/ammun/4.jpg",
        thumbnailWidth: 200,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/5.jpg",
        thumbnail: "/project/small/ammun/5.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/6.jpg",
        thumbnail: "/project/small/ammun/6.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/7.jpg",
        thumbnail: "/project/small/ammun/7.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/8.jpg",
        thumbnail: "/project/small/ammun/8.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/9.jpg",
        thumbnail: "/project/small/ammun/9.jpg",
        thumbnailWidth: 356,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/10.jpg",
        thumbnail: "/project/small/ammun/10.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/11.jpg",
        thumbnail: "/project/small/ammun/11.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/12.jpg",
        thumbnail: "/project/small/ammun/12.jpg",
        thumbnailWidth: 128,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/13.jpg",
        thumbnail: "/project/small/ammun/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/14.jpg",
        thumbnail: "/project/small/ammun/14.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/15.jpg",
        thumbnail: "/project/small/ammun/15.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/16.jpg",
        thumbnail: "/project/small/ammun/16.jpg",
        thumbnailWidth: 200,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/17.jpg",
        thumbnail: "/project/small/ammun/17.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/18.jpg",
        thumbnail: "/project/small/ammun/18.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const opticImages = [
    {   src: "/project/large/optic/1.jpg",
        thumbnail: "/project/small/optic/1.jpg",
        thumbnailWidth: 152,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/2.jpg",
        thumbnail: "/project/small/optic/2.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/3.jpg",
        thumbnail: "/project/small/optic/3.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/4.jpg",
        thumbnail: "/project/small/optic/4.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/5.jpg",
        thumbnail: "/project/small/optic/5.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/6.jpg",
        thumbnail: "/project/small/optic/6.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/7.jpg",
        thumbnail: "/project/small/optic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/8.jpg",
        thumbnail: "/project/small/optic/8.jpg",
        thumbnailWidth: 138,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/9.jpg",
        thumbnail: "/project/small/optic/9.jpg",
        thumbnailWidth: 121,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/10.jpg",
        thumbnail: "/project/small/optic/10.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/11.jpg",
        thumbnail: "/project/small/optic/11.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const autoImages = [
    {   src: "/project/large/auto/1.jpg",
        thumbnail: "/project/small/auto/1.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/2.jpg",
        thumbnail: "/project/small/auto/2.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/3.jpg",
        thumbnail: "/project/small/auto/3.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/4.jpg",
        thumbnail: "/project/small/auto/4.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/5.jpg",
        thumbnail: "/project/small/auto/5.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const productImages = [
    {   src: "/project/large/product/1.jpg",
        thumbnail: "/project/small/product/1.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/2.jpg",
        thumbnail: "/project/small/product/2.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/3.jpg",
        thumbnail: "/project/small/product/3.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/4.jpg",
        thumbnail: "/project/small/product/4.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/5.jpg",
        thumbnail: "/project/small/product/5.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/6.jpg",
        thumbnail: "/project/small/product/6.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/7.jpg",
        thumbnail: "/project/small/product/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/8.jpg",
        thumbnail: "/project/small/product/8.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/9.jpg",
        thumbnail: "/project/small/product/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/10.jpg",
        thumbnail: "/project/small/product/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/11.jpg",
        thumbnail: "/project/small/product/11.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/12.jpg",
        thumbnail: "/project/small/product/12.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/13.jpg",
        thumbnail: "/project/small/product/13.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/14.jpg",
        thumbnail: "/project/small/product/14.jpg",
        thumbnailWidth: 113,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/15.jpg",
        thumbnail: "/project/small/product/15.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/16.jpg",
        thumbnail: "/project/small/product/16.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/17.jpg",
        thumbnail: "/project/small/product/17.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/18.jpg",
        thumbnail: "/project/small/product/18.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/19.jpg",
        thumbnail: "/project/small/product/19.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/20.jpg",
        thumbnail: "/project/small/product/20.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"}
]

export const fondImages = [
    {   src: "/project/large/fond/1.jpg",
        thumbnail: "/project/small/fond/1.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/2.jpg",
        thumbnail: "/project/small/fond/2.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/3.jpg",
        thumbnail: "/project/small/fond/3.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/4.jpg",
        thumbnail: "/project/small/fond/4.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/5.jpg",
        thumbnail: "/project/small/fond/5.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/6.jpg",
        thumbnail: "/project/small/fond/6.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/7.jpg",
        thumbnail: "/project/small/fond/7.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/8.jpg",
        thumbnail: "/project/small/fond/8.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/9.jpg",
        thumbnail: "/project/small/fond/9.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/10.jpg",
        thumbnail: "/project/small/fond/10.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/11.jpg",
        thumbnail: "/project/small/fond/11.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/12.jpg",
        thumbnail: "/project/small/fond/12.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/13.jpg",
        thumbnail: "/project/small/fond/13.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/14.jpg",
        thumbnail: "/project/small/fond/14.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/15.jpg",
        thumbnail: "/project/small/fond/15.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/16.jpg",
        thumbnail: "/project/small/fond/16.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/17.jpg",
        thumbnail: "/project/small/fond/17.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/18.jpg",
        thumbnail: "/project/small/fond/18.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/19.jpg",
        thumbnail: "/project/small/fond/19.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/20.jpg",
        thumbnail: "/project/small/fond/20.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/21.jpg",
        thumbnail: "/project/small/fond/21.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/22.jpg",
        thumbnail: "/project/small/fond/22.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/23.jpg",
        thumbnail: "/project/small/fond/23.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/24.jpg",
        thumbnail: "/project/small/fond/24.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/25.jpg",
        thumbnail: "/project/small/fond/25.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/26.jpg",
        thumbnail: "/project/small/fond/26.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/27.jpg",
        thumbnail: "/project/small/fond/27.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/28.jpg",
        thumbnail: "/project/small/fond/28.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/29.jpg",
        thumbnail: "/project/small/fond/29.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/30.jpg",
        thumbnail: "/project/small/fond/30.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/31.jpg",
        thumbnail: "/project/small/fond/31.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/32.jpg",
        thumbnail: "/project/small/fond/32.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/33.jpg",
        thumbnail: "/project/small/fond/33.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/34.jpg",
        thumbnail: "/project/small/fond/34.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/35.jpg",
        thumbnail: "/project/small/fond/35.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/36.jpg",
        thumbnail: "/project/small/fond/36.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/37.jpg",
        thumbnail: "/project/small/fond/37.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/38.jpg",
        thumbnail: "/project/small/fond/38.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/39.jpg",
        thumbnail: "/project/small/fond/39.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/40.jpg",
        thumbnail: "/project/small/fond/40.jpg",
        /*thumbnailWidth: 433,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/41.jpg",
        thumbnail: "/project/small/fond/41.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/42.jpg",
        thumbnail: "/project/small/fond/42.jpg",
        /*thumbnailWidth: 151,
        thumbnailHeight: 200,*/
        caption: "first image"},
    {   src: "/project/large/fond/43.jpg",
        thumbnail: "/project/small/fond/43.jpg",
        /*thumbnailWidth: 267,
        thumbnailHeight: 200,*/
        caption: "first image"},

]