export const medicImages = [
    {   src: "/project/large/medic/1.jpg",
        thumbnail: "/project/small/medic/1.jpg",
        thumbnailWidth: 113,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/2.jpg",
        thumbnail: "/project/small/medic/2.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/3.jpg",
        thumbnail: "/project/small/medic/3.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/4.jpg",
        thumbnail: "/project/small/medic/4.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/5.jpg",
        thumbnail: "/project/small/medic/5.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/6.jpg",
        thumbnail: "/project/small/medic/6.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/7.jpg",
        thumbnail: "/project/small/medic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/8.jpg",
        thumbnail: "/project/small/medic/8.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/9.jpg",
        thumbnail: "/project/small/medic/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/10.jpg",
        thumbnail: "/project/small/medic/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/11.jpg",
        thumbnail: "/project/small/medic/11.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/12.jpg",
        thumbnail: "/project/small/medic/12.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/13.jpg",
        thumbnail: "/project/small/medic/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/14.jpg",
        thumbnail: "/project/small/medic/14.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const ammunImages = [
    {   src: "/project/large/ammun/1.jpg",
        thumbnail: "/project/small/ammun/1.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/2.jpg",
        thumbnail: "/project/small/ammun/2.jpg",
        thumbnailWidth: 356,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/3.jpg",
        thumbnail: "/project/small/ammun/3.jpg",
        thumbnailWidth: 356,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/4.jpg",
        thumbnail: "/project/small/ammun/4.jpg",
        thumbnailWidth: 200,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/5.jpg",
        thumbnail: "/project/small/ammun/5.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/6.jpg",
        thumbnail: "/project/small/ammun/6.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/7.jpg",
        thumbnail: "/project/small/ammun/7.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/8.jpg",
        thumbnail: "/project/small/ammun/8.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/9.jpg",
        thumbnail: "/project/small/ammun/9.jpg",
        thumbnailWidth: 356,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/10.jpg",
        thumbnail: "/project/small/ammun/10.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/11.jpg",
        thumbnail: "/project/small/ammun/11.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/12.jpg",
        thumbnail: "/project/small/ammun/12.jpg",
        thumbnailWidth: 128,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/13.jpg",
        thumbnail: "/project/small/ammun/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/14.jpg",
        thumbnail: "/project/small/ammun/14.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/15.jpg",
        thumbnail: "/project/small/ammun/15.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/16.jpg",
        thumbnail: "/project/small/ammun/16.jpg",
        thumbnailWidth: 200,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/17.jpg",
        thumbnail: "/project/small/ammun/17.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/ammun/18.jpg",
        thumbnail: "/project/small/ammun/18.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const opticImages = [
    {   src: "/project/large/optic/1.jpg",
        thumbnail: "/project/small/optic/1.jpg",
        thumbnailWidth: 152,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/2.jpg",
        thumbnail: "/project/small/optic/2.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/3.jpg",
        thumbnail: "/project/small/optic/3.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/4.jpg",
        thumbnail: "/project/small/optic/4.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/5.jpg",
        thumbnail: "/project/small/optic/5.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/6.jpg",
        thumbnail: "/project/small/optic/6.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/7.jpg",
        thumbnail: "/project/small/optic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/8.jpg",
        thumbnail: "/project/small/optic/8.jpg",
        thumbnailWidth: 138,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/9.jpg",
        thumbnail: "/project/small/optic/9.jpg",
        thumbnailWidth: 121,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/10.jpg",
        thumbnail: "/project/small/optic/10.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/optic/11.jpg",
        thumbnail: "/project/small/optic/11.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const autoImages = [
    {   src: "/project/large/auto/1.jpg",
        thumbnail: "/project/small/auto/1.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/2.jpg",
        thumbnail: "/project/small/auto/2.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/3.jpg",
        thumbnail: "/project/small/auto/3.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/4.jpg",
        thumbnail: "/project/small/auto/4.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/5.jpg",
        thumbnail: "/project/small/auto/5.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},

]
export const productImages = [
    {   src: "/project/large/product/1.jpg",
        thumbnail: "/project/small/product/1.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/2.jpg",
        thumbnail: "/project/small/product/2.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/3.jpg",
        thumbnail: "/project/small/product/3.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/4.jpg",
        thumbnail: "/project/small/product/4.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/5.jpg",
        thumbnail: "/project/small/product/5.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/6.jpg",
        thumbnail: "/project/small/product/6.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/7.jpg",
        thumbnail: "/project/small/product/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/8.jpg",
        thumbnail: "/project/small/product/8.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/9.jpg",
        thumbnail: "/project/small/product/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/10.jpg",
        thumbnail: "/project/small/product/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/11.jpg",
        thumbnail: "/project/small/product/11.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/12.jpg",
        thumbnail: "/project/small/product/12.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/13.jpg",
        thumbnail: "/project/small/product/13.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/14.jpg",
        thumbnail: "/project/small/product/14.jpg",
        thumbnailWidth: 113,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/15.jpg",
        thumbnail: "/project/small/product/15.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/16.jpg",
        thumbnail: "/project/small/product/16.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/17.jpg",
        thumbnail: "/project/small/product/17.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/18.jpg",
        thumbnail: "/project/small/product/18.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/19.jpg",
        thumbnail: "/project/small/product/19.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/product/20.jpg",
        thumbnail: "/project/small/product/20.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"}
]

export const fondImages = [
    {   src: "/project/large/auto/1.jpg",
        thumbnail: "/project/small/auto/1.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/2.jpg",
        thumbnail: "/project/small/auto/2.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/3.jpg",
        thumbnail: "/project/small/auto/3.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/4.jpg",
        thumbnail: "/project/small/auto/4.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/auto/5.jpg",
        thumbnail: "/project/small/auto/5.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},

]