export const reportImages = [
    {   src: "/fond/report/large/1.jpg",
        thumbnail: "/fond/report/small/1.jpg",
        thumbnailWidth: 400,
        thumbnailHeight: 301,
        caption: "Фото 1"},
    {   src: "/fond/report/large/2.jpg",
        thumbnail: "/fond/report/small/2.jpg",
        thumbnailWidth: 400,
        thumbnailHeight: 301,
        caption: "Фото 2"},
    {   src: "/fond/report/large/3.jpg",
        thumbnail: "/fond/report/small/3.jpg",
        thumbnailWidth: 400,
        thumbnailHeight: 225,
        caption: "Фото 3"},
    {   src: "/fond/report/large/4.jpg",
        thumbnail: "/fond/report/small/4.jpg",
        thumbnailWidth: 400,
        thumbnailHeight: 257,
        caption: "Фото 4"},
   /* {   src: "/documents/large/statut3.jpg",
        thumbnail: "/documents/small/statut3.jpg",
        thumbnailWidth: 180,
        thumbnailHeight: 400,
        caption: "first image"},
    /*{   src: "/project/large/medic/6.jpg",
        thumbnail: "/project/small/medic/6.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/7.jpg",
        thumbnail: "/project/small/medic/7.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/8.jpg",
        thumbnail: "/project/small/medic/8.jpg",
        thumbnailWidth: 266,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/9.jpg",
        thumbnail: "/project/small/medic/9.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/10.jpg",
        thumbnail: "/project/small/medic/10.jpg",
        thumbnailWidth: 150,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/11.jpg",
        thumbnail: "/project/small/medic/11.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/12.jpg",
        thumbnail: "/project/small/medic/12.jpg",
        thumbnailWidth: 151,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/13.jpg",
        thumbnail: "/project/small/medic/13.jpg",
        thumbnailWidth: 433,
        thumbnailHeight: 200,
        caption: "first image"},
    {   src: "/project/large/medic/14.jpg",
        thumbnail: "/project/small/medic/14.jpg",
        thumbnailWidth: 267,
        thumbnailHeight: 200,
        caption: "first image"},
*/
]
