import React from "react";
import Head from "next/head";
import LayoutMain from "../components/LayoutMain";
import Gallery from "react-grid-gallery";
import {productImages} from "../components/ProjectImages";
import {docImages} from "../components/DocImages";

export default function DocPage() {
    const docList = [
        {
           path: "/documents/dovidka1.jpg",
           name: "Довідка 1"

        }
    ]
    return (
    <>
        <Head>
            <title>Melek</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <LayoutMain>

            <h1 className="text-center">Документи Благодійного фонду "Melek"</h1>

            <div style={{
                display: "block",
                minHeight: "1px",
                width: "100%",
                border: "1px solid #ddd",
                overflow: "auto"
            }}>
                <Gallery
                    images={docImages}
                    enableLightbox={true}
                    enableImageSelection={false}
                    backdropClosesModal={true}
                    margin={50}
                />

            </div>

        </LayoutMain>
    </>
)
}