import React from "react";
import Head from "next/head";
import LayoutMain from "../components/LayoutMain";
import Container from "react-bootstrap/Container";
import Gallery from "react-grid-gallery";
import {fondImages} from "../components/FondImages";

export default function Fond() {
        return (
         <>
             <Head>
                 <title>Новини</title>
                 <meta name="description" content="Generated by create next app"/>
                 <link rel="icon" href="/favicon.ico"/>
             </Head>
             <LayoutMain>

                 <Container>

                     <h1>Історія Фонду</h1>
                     <h3>Місія Фонду</h3>
                     <h3>Відзнаки Фонду</h3>
                     <h1 className="text-center">Відзнаки Благодійного фонду "Melek"</h1>

                     <div style={{
                         display: "block",
                         minHeight: "1px",
                         width: "100%",
                         border: "1px solid #ddd",
                         overflow: "auto"
                     }}>
                         <Gallery
                             images={fondImages}
                             enableLightbox={true}
                             enableImageSelection={false}
                             backdropClosesModal={true}
                             margin={50}
                         />

                     </div>

                 </Container>


             </LayoutMain>
         </>
        )
}