import Head from 'next/head'
import React from "react";
import Container from "react-bootstrap/Container";
import LayoutMain from "../components/LayoutMain";
import PayForm from "../components/PayForm";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Image from "next/image"



export default function Home() {
    return (
        <>
            <Head>
                <title>Melek</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <LayoutMain>

                        <Row >
                            <Col className="mt-2">
                        <Image src="/mainImg.jpg" width={1000} height={600}/>
                            </Col>
                            <Col>
                        <PayForm />

                            </Col>
                        </Row>


            </LayoutMain>

        </>
    )
}
{/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>*/
}