import Head from 'next/head'
import React, {useCallback, useContext, useEffect} from "react";
import Container from "react-bootstrap/Container";
import LayoutMain from "../components/LayoutMain";
import PayForm from "../components/PayForm";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Image from "next/image"
import CarouselFade from "../components/CarouselFade";
import CardHelp from "../components/CardHelp";
import Button from "react-bootstrap/Button";
import AppContext from "../context/AppContext";
import Link from "next/link";


export default function Home(props) {

    const warData = {day: props.warData.data.day, person: props.warData.data.stats.personnel_units}
    const [warString,setWarString] = useContext(AppContext)

    const loadData = useCallback(()=>{
        setWarString(warData)
    },[])

    useEffect(()=>{
        loadData()
    },[])

    return (
        <>
            <Head>
                <title>Melek</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <LayoutMain props={warString}>

                <Row>
                    <CarouselFade/>
                </Row>
                <Row className="text-center mt-4">
                    <h1>Головна наша місія - Допомога тим, хто найбільше цього потребує</h1>
                    <h4>Наш Фонд був заснований у 2018 році, кожного дня наша команда волонтерів працює задля
                        досягнення спільної мети. Разом з нашими партнерами та благодійниками ми реалізуємо дуже важливі
                        проекти
                    </h4>
                    <h2 className="mt-5 mb-4">Чим ми займаємось</h2>
                    <h3 className="text-decoration-underline mb-4">Допомога ЗСУ</h3>
                </Row>
{/*-----------------------------------------------Cards help for AFU---------------------------------------------------*/}
                <Row className="justify-content-center">
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/javel.jpg"
                            pathBack="/myMono.jpg"
                            activeKey="medicine"
                            tittle="Польова війскова медицина"
                            textContent="Збираємо індивідуальні війскові аптечки(для першої допомоги)
                                            та набори для польових медиків/санчасті"
                        />
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/javel.jpg"
                            pathBack="/myMono.jpg"
                            activeKey="ammunition"
                            tittle="Амуніція"
                            textContent="виготовляємо наколінники, розгрузки, рпс, плитоноски, підсумок
                                  сбросу, підсумки під аптечку, під турнікет, стропа евакуації,
                                  кікімора (шугайстр)"
                        />
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/javel.jpg"
                            pathBack="/myMono.jpg"
                            activeKey="optic"
                            tittle="Оптика"
                            textContent="Закуповуємо прибори нічного бачення, біноклі, тепловізори, захисні окуляри,
                                   монокуляри"
                        />
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/javel.jpg"
                            pathBack="/myMono.jpg"
                            activeKey="car"
                            tittle="Транспорт"
                            textContent="Пошук, закупівля, ремонт,
                                        фарбування автівок для ЗСУ"/>
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/javel.jpg"
                            pathBack="/myMono.jpg"
                            activeKey="product"
                            tittle="Харчування"
                            textContent="Виготовлення субліматів, тушонки, консервів, кондитерських виробів. Постачання
                                    води, овочів, крупи, консервації"
                        />
                    </Col>
                </Row>
{/*-----------------------------------------------Cards help for people------------------------------------------------*/}
                <Row>
                    <h3 className="text-decoration-underline text-center mb-4 mt-5">Допомога ВПО та СЖО</h3>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/product.jpg"
                            pathBack="/myMono.jpg"
                            tittle="Харчова допомога"
                            textContent="Допомагаємо продуктами
                                        харчування ВПО та СЖО"
                        />
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/clothes.jpg"
                            pathBack="/myMono.jpg"
                            tittle="Одяг та предмети побуту"
                            textContent="Забеспечуємо одягом, взуттям, посудом та іншими предметами першої необхідності"
                        />
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={4}>
                        <CardHelp
                            pathFront="/child.jpg"
                            pathBack="/myMono.jpg"
                            tittle="Дитячі товари та харчування"
                            textContent="Забеспечення найменших громадян предметами дитячої гігієни,
                                     одягом, дитячими візочками та харчуванням. Співпрацюємо з
                                    дитячими будинками"
                        />
                    </Col>
                    <Col className="d-flex justify-content-center mb-4" xs={12} md={6} lg={12}>
                        <CardHelp
                            pathFront="/lawer.jpg"
                            pathBack="/myMono.jpg"
                            tittle="Юридична допомога"
                            textContent="Надання безкоштовної юр.
                                    допомоги, консультація з приводу майна, відновлення втраченних документів,
                                    оформлення юр.послуг"
                        />
                    </Col>
{/*---------------------------------------------------------------------------------------------------------------------*/}
                </Row>
                <Row className="text-center justify-content-center mt-4 ">
                    <h3>Збір коштів на потреби ЗСУ</h3>
                    <h5>До нас щодня звертаються війскові частини з проханням допомгти їм з придбанням необхідних речей,
                        тактичного обладнання, авто тощо...
                    </h5>
                    <h4>Відкриті проекти</h4>
                    <Row className=" justify-content-center w-75">

                        <PayForm/>

                        <Link href="/news">
                        <Button variant="outline-dark mt-5 mb-5 btn-block" size="lg" style={{height: "100px"}}>
                            Збір речей для бійців на "Нулі"
                        </Button>
                        </Link>

                    </Row>
                </Row>

            </LayoutMain>

        </>
    )
}

export async function getServerSideProps() {
    const res = await fetch("https://russianwarship.rip/api/v1/statistics/latest")
    const warData = await res.json()

    return {
        props: {warData}
    }
}
