import React from "react";
import Row from "react-bootstrap/Row";
import Head from "next/head";
import Image from "next/image";
import Accordion from "react-bootstrap/Accordion"
import LayoutMain from "../components/LayoutMain";
import Container from "react-bootstrap/Container";
import styles from "../styles/Projects.module.css";

export default function projects() {
    return (
        <>
            <Head>
                <title>Payment</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <LayoutMain>
                <Container>
                    <Accordion defaultActiveKey="0">
                        <Accordion.Item eventKey="0" >
                            <Accordion.Header >Польова війскова медицина</Accordion.Header>
                            <Accordion.Body >
                                <Container className="d-flex justify-content-between ju">
                                <img src="/cat.jpg" width={200} height={200} className={styles.scale}/>
                                <Image src="/cat.jpg" width={200} height={200} />
                                <Image src="/cat.jpg" width={200} height={200} />
                                <Image src="/cat.jpg" width={200} height={200} />
                                <Image src="/cat.jpg" width={200} height={200} />
                                </Container>
                            </Accordion.Body>
                        </Accordion.Item>
                        <Accordion.Item eventKey="1">
                            <Accordion.Header>Accordion Item #2</Accordion.Header>
                            <Accordion.Body>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                                minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                                aliquip ex ea commodo consequat. Duis aute irure dolor in
                                reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                                pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                                culpa qui officia deserunt mollit anim id est laborum.
                            </Accordion.Body>
                        </Accordion.Item>
                    </Accordion>
                </Container>
            </LayoutMain>

        </>
    )
}